---
# Source: grafana/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: grafana
    chart: grafana-3.7.3
    heritage: Tiller
    release: release-name
  name: release-name-grafana
  namespace: default
