---
# Source: opencart/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-opencart
  labels:
    app: release-name-opencart
    chart: opencart-7.0.15
    release: "release-name"
    heritage: "Tiller"
type: Opaque
data:
  
  opencart-password: "cEM4OWp5M21Xeg=="
  
  smtp-password: ""
