= k8s-update-secrets(1)
ilearndevops@gmail.com
v1.0.0
:doctype: manpage
:manmanual: k8s-update-secrets
:mansource: k8s-update-secrets
:man-linkstyle: pass:[blue R < >]

== Name

k8s-update-secrets - Update the value of single secret with value of namespace append to the original secret 

== Synopsis

*k8s-update-secrets* [--help] [[-- secret <k8s-secret/database-ro>] [--secretkey <secretkey/DATABASE_NAME>] [--secretvalue <secretvalue/redis>] [-- namespace <namespace/marsel>]

== Description

This script updates the k8s-secret value by appending the namespace to the original secret. The script is typically used to overwrite the secret (db/redis) in the personal namespaces and will called in deploy script when stages are other than dev/production.



== Options

*--help, -h*::
  Print this man page.
*--secretkey, -k*::
  Name of the secret key that needs to be updated.
*--secretvalue, -v*::
  Value of the secret key that need to be modified/appended.
*--secret, -s*::
  Name of the k8s-secret
*--namespace, -n*::
  Name of the namespace in which secret exists. 


== Exit status

*0*::
  Success.
  Secret key value is will be modified.

*1*::
  Failure.
  Script will fail on the pod if any of the arguments are passed and secret will  not be modified.

== See also

* << get-stage-from-branch>>

== Copyright

Copyright (C) 2020 312-school +
