apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::401413892014:role/eks-dev-workers-NodeInstanceRole-MMUVN9IDLNF3
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
        # next line allows deployments (jenkins)
        - system:masters
    - rolearn: arn:aws:iam::401413892014:role/DevopsAccessRole2020B
      username: devops2020B
      groups:
        - system:masters
