apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [auth.anonymous]
    enabled = true
    # Organization name that should be used for unauthenticated users
    org_name = Main Org.
    # Role for unauthenticated users, other valid values are `Editor` and `Admin`
    org_role = Viewer
  ldap.toml: ""
kind: ConfigMap
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: NAMESPACE
